### ISSUE TITLE
[Idea] Auto send dummy requests to avoid/limit timeout

### ISSUE THREAD

**Issue by AliSoftware** [Shuunen/a-better-syges#2]
Maybe it would be possible to keep the connection active a little longer by sending dummy/noop requests in the background every N minutes, to avoid the super-short session timeout to be a PITA?

**Comment by Shuunen** [comment]
Yep good idea, session timeout is so short by default :disappointed:

**Comment by Shuunen** [comment]
@AliSoftware this https://github.com/Shuunen/a-better-syges/commit/e9e4212e0f1c9fb1ab5831bf69f1dd37ce8a7ce8 should do the trick :)
